version: '3'

services:
  poke-api:
    build: .
    container_name: poke-api
    entrypoint:
      - /entrypoint.sh
    ports:
    - 8080:8080
    tty: true
    volumes:
      - ./app:/app
    image: dasa/poke-api:latest